name: Deploy Docs
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "packages/docs/**/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
        with:
          install: false
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          check-latest: true
          package-manager-cache: false
      - run: pnpm config set --location=global minimumReleaseAge 0
      - run: pnpm install
      - run: pnpm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/out
      - uses: actions/deploy-pages@v4
        id: deployment
